Gebruik maken van SKU db (usage documentation followed from: https://docs.ultralytics.com/datasets/detect/sku-110k/#dataset-yaml)

In [10]:
from ultralytics import YOLO, RTDETR
from transformers import Owlv2Processor, Owlv2ForObjectDetection, MobileViTImageProcessor, MobileViTModel, AutoProcessor, AutoModelForCausalLM
import torch
from nanoowl.owl_predictor import OwlPredictor
from PIL import Image
import cv2
import sys
import types
import importlib.machinery
import os


In [ ]:
# Load a model
model1 = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Train the model
results = model1.train(data="SKU-110K.yaml", epochs=50, imgsz=416, batch=32,  workers=8, device=0, verbose=False)

Ultralytics 8.4.37  Python-3.11.9 torch-2.11.0+cpu CPU (AMD Ryzen 7 7840HS w/ Radeon 780M Graphics)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=SKU-110K.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100,

In [2]:
model2 = YOLO("yolo11s.pt")
results = model2.train(data="SKU-110K.yaml", epochs=50, imgsz=416, batch=16,  workers=4, device=0, verbose=False, name="yolo11s_SKU110K")

Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=SKU-110K.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=416, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11s_SKU110K5, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True,

In [5]:
%pip install git+https://github.com/NVIDIA-AI-IOT/nanoowl

  Cloning https://github.com/NVIDIA-AI-IOT/nanoowl to C:\Users\krist\AppData\Local\Temp\pip-req-build-4xyvhzbo
  Resolved https://github.com/NVIDIA-AI-IOT/nanoowl to commit fb553dee4c58f8c53ec2bf01f355a54648e67dbd
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for nanoowl: filename=nanoowl-0.0.0-py3-none-any.whl size=27414 sha256=65faee752961e1892728c467950570d7f1ebae379bfc45596c12ad79416ddf28
  Stored in directory: C:\Users\krist\AppData\Local\Temp\pip-ephem-wheel-cache-8xks3uvs\wheels\89\06\45\ecb771209ce4efebeb548676c3c3674c27fb633400d5a7787c
Successfully built nanoowl
Note: you may need to restart the kernel to use updated packages.


  Running command git clone --filter=blob:none --quiet https://github.com/NVIDIA-AI-IOT/nanoowl 'C:\Users\krist\AppData\Local\Temp\pip-req-build-4xyvhzbo'


In [3]:
# Use the best model
model1 = YOLO(r'C:\Users\krist\runs\detect\train\weights\best.pt')
model2 = YOLO(r'C:\Users\krist\runs\detect\yolo11s_SKU110K5\weights\best.pt')

In [6]:
model1.val(data="SKU-110K.yaml", split="test")
model2.val(data="SKU-110K.yaml", split="test")

Ultralytics 8.4.37  Python-3.11.9 torch-2.6.0+cu124 CUDA:0 (NVIDIA GeForce RTX 4070 Laptop GPU, 8188MiB)
Model summary (fused): 73 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access  (ping: 0.30.1 ms, read: 79.914.2 MB/s, size: 1014.0 KB)
val: Scanning C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\labels... 2935 images, 0 backgrounds, 1 corrupt: 100% ━━━━━━━━━━━━ 2936/2936 214.1it/s 13.7s0.1s
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1029.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_1035.jpg: corrupt JPEG restored and saved
val: C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000025389405090>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.0480

In [ ]:
# Test on new images
results1 = model1.predict(source='path-unseen-pictures', save=True)
results2 = model2.predict(source='path-unseen-pictures', save=True)

In [ ]:
predictor = OwlPredictor()

image_cv = cv2.imread(r"C:\Users\krist\Downloads\testimage.webp")

image = Image.fromarray(cv2.cvtColor(image_cv, cv2.COLOR_BGR2RGB))

texts = [["can", "soda can", "aluminium can", "soft drink can"]]

text_encodings = predictor.encode_text(texts)

predictions = predictor.predict(
    image=image,
    text_encodings=text_encodings,
    text=texts
)

boxes = predictions.boxes
scores = predictions.scores
labels = predictions.labels

Loading weights: 100%|██████████| 412/412 [00:00<00:00, 4985.48it/s]


In [22]:
boxes, scores, labels

(tensor([[131.0309,  22.6032, 370.4557, 465.1947]], device='cuda:0',
        grad_fn=<IndexBackward0>),
 tensor([0.2274], device='cuda:0', grad_fn=<IndexBackward0>),
 tensor([3], device='cuda:0'))

In [12]:
flash_attn = types.ModuleType("flash_attn")
flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", None)

flash_attn_interface = types.ModuleType("flash_attn.flash_attn_interface")
flash_attn_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", None)

sys.modules["flash_attn"] = flash_attn
sys.modules["flash_attn.flash_attn_interface"] = flash_attn_interface

os.environ["FLASH_ATTENTION_FORCE_DISABLED"] = "1"

model_id = "microsoft/Florence-2-base"

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)

model3 = AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    attn_implementation="eager"
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model3 = model3.to(device)

image = Image.open(r"C:\Users\krist\Documents\Hogent_IT\3de_jaar\Bachelorproef\bachproef26\latex-hogent-bachproef\bachproef\datasets\SKU-110K_fixed\images\test_0.jpg").convert("RGB")

task = "<DETAILED_CAPTION>"

inputs = processor(text=task, images=image, return_tensors="pt").to(device)

generated_ids = model3.generate(**inputs, max_new_tokens=100)
result = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(result)

The image shows a grocery store filled with lots of different types of food, including bottles, packets, and other objects arranged in racks. The floor is visible at the bottom of the image.
